esphome:
  name: vaillant-heizung

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "1234567"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  
web_server:
  port: 80
  
output:
  - platform: ledc
    pin: GPIO27
    id: temp_789
    frequency: 30kHz
    min_power: 0.01
    max_power: 1

light:
  - platform: monochromatic
    name: "Vorlauftemperatur Sollwert"
    output: temp_789
